souffle: souffle::RamUserDefinedOperator Class Reference
souffle::RamUserDefinedOperator Class Reference
Unary user-defined function.
#include <RamValue.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
arguments (std::move(args))
RamUserDefinedOperator * clone () const override
Create clone.
const RamValue * getArg (size_t i) const
size_t getArgCount () const
std::vector< RamValue * > getArguments () const
Get values.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
size_t getLevel () const override
Get level.
const std::string & getName () const
const std::string & getType () const
name (n)
void print (std::ostream &os) const override
Print.
RamUserDefinedOperator (const std::string &n, const std::string &t, std::vector< std::unique_ptr< RamValue >> args)
type (t)
Public Member Functions inherited from souffle::RamValue
bool isConstant () const
Determines whether this value is a constant or not.
RamValue (RamNodeType type, bool isCnst)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
std::vector< std::unique_ptr
< RamValue > > arguments
Argument of unary function.
const std::string name
Name of user-defined unary functor.
const std::string type
Argument type.
Additional Inherited Members
Protected Attributes inherited from souffle::RamValue
bool cnst
Detailed Description
Unary user-defined function.
Definition at line 131 of file RamValue.h.
Constructor & Destructor Documentation
souffle::RamUserDefinedOperator::RamUserDefinedOperator (const std::string & n, const std::string & t, std::vector< std::unique_ptr< RamValue >> args) inline
Definition at line 143 of file RamValue.h.
Referenced by clone().
             : RamValue(RN_UserDefinedOperator,
                       all_of(args, [](const std::unique_ptr<RamValue>& a) { return a && a->isConstant(); })),
Member Function Documentation
void souffle::RamUserDefinedOperator::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 210 of file RamValue.h.
References arguments, and map.
{
         for (auto& arg : arguments) {
             arg = map(std::move(arg));
         }
     }
souffle::RamUserDefinedOperator::arguments (std:: moveargs)
RamUserDefinedOperator* souffle::RamUserDefinedOperator::clone () const inline override virtual
Create clone.
Implements souffle::RamValue.
Definition at line 200 of file RamValue.h.
References arguments, souffle::RamValue::clone(), name, RamUserDefinedOperator(), and type.
{
         RamUserDefinedOperator* res = new RamUserDefinedOperator(name, type, {});
         for (auto& cur : arguments) {
             RamValue* arg = cur->clone();
             res->arguments.push_back(std::unique_ptr<RamValue>(arg));
         }
         return res;
     }
bool souffle::RamUserDefinedOperator::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 218 of file RamValue.h.
References arguments, souffle::equal_targets(), name, and type.
{
         assert(nullptr != dynamic_cast<const RamUserDefinedOperator*>(&node));
         const auto& other = static_cast<const RamUserDefinedOperator&>(node);
         return name == other.name && type == other.type && equal_targets(arguments, other.arguments);
     }
const RamValue* souffle::RamUserDefinedOperator::getArg (size_t i) const inline
Definition at line 162 of file RamValue.h.
References arguments, and i.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalVal().
{
         return arguments[i].get();
     }
size_t souffle::RamUserDefinedOperator::getArgCount () const inline
Definition at line 166 of file RamValue.h.
References arguments.
Referenced by souffle::Interpreter::evalVal().
{
         return arguments.size();
     }
std::vector<RamValue*> souffle::RamUserDefinedOperator::getArguments () const inline
Get values.
Definition at line 158 of file RamValue.h.
References arguments, and souffle::toPtrVector().
{
         return toPtrVector(arguments);
     }
std::vector<const RamNode*> souffle::RamUserDefinedOperator::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 191 of file RamValue.h.
References arguments.
{
         std::vector<const RamNode*> res;
         for (const auto& cur : arguments) {
             res.push_back(cur.get());
         }
         return res;
     }
size_t souffle::RamUserDefinedOperator::getLevel () const inline override virtual
Get level.
Implements souffle::RamValue.
Definition at line 180 of file RamValue.h.
References arguments.
{
         size_t level = 0;
         for (const auto& arg : arguments) {
             if (arg) {
                 level = std::max(level, arg->getLevel());
             }
         }
         return level;
     }
const std::string& souffle::RamUserDefinedOperator::getName () const inline
Definition at line 170 of file RamValue.h.
References name.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalVal(), and souffle::Synthesiser::generateCode().
{
         return name;
     }
const std::string& souffle::RamUserDefinedOperator::getType () const inline
Definition at line 174 of file RamValue.h.
References type.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalVal(), and souffle::Synthesiser::generateCode().
{
         return type;
     }
souffle::RamUserDefinedOperator::name (n)
void souffle::RamUserDefinedOperator::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 150 of file RamValue.h.
References arguments, souffle::join(), name, and type.
{
         os << "@" << name << "_" << type << "(";
         os << join(
                 arguments, ",", [](std::ostream& out, const std::unique_ptr<RamValue>& arg) { out << *arg; });
         os << ")";
     }
souffle::RamUserDefinedOperator::type (t) inline
Definition at line 147 of file RamValue.h.
 {}
Field Documentation
std::vector<std::unique_ptr<RamValue> > souffle::RamUserDefinedOperator::arguments private
Argument of unary function.
Definition at line 134 of file RamValue.h.
Referenced by apply(), clone(), equal(), getArg(), getArgCount(), getArguments(), getChildNodes(), getLevel(), and print().
const std::string souffle::RamUserDefinedOperator::name private
Name of user-defined unary functor.
Definition at line 137 of file RamValue.h.
Referenced by clone(), equal(), getName(), and print().
const std::string souffle::RamUserDefinedOperator::type private
Argument type.
Definition at line 140 of file RamValue.h.
Referenced by clone(), equal(), getType(), and print().
The documentation for this class was generated from the following file:
RamValue.h