souffle: souffle::AstUserDefinedFunctor Class Reference
souffle::AstUserDefinedFunctor Class Reference
Subclass of Argument that represents a unary function.
#include <AstArgument.h>
Public Member Functions
void add (std::unique_ptr< AstArgument > arg)
add argument to argument list
void apply (const AstNodeMapper &map) override
Mutates this node.
AstUserDefinedFunctor ()
AstUserDefinedFunctor (const std::string &name)
AstUserDefinedFunctor * clone () const override
Create clone.
const AstArgument * getArg (size_t idx) const
get argument
size_t getArgCount () const
get number of arguments
std::vector< AstArgument * > getArguments () const
get arguments
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
const std::string & getName () const
get name
void print (std::ostream &os) const override
print user-defined functor
void setName (const std::string &n)
set name
~AstUserDefinedFunctor () override=default
Public Member Functions inherited from souffle::AstArgument
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
std::vector< std::unique_ptr
< AstArgument > > args
arguments of user-defined functor
std::string name
name of user-defined functor
Detailed Description
Subclass of Argument that represents a unary function.
Definition at line 356 of file AstArgument.h.
Constructor & Destructor Documentation
souffle::AstUserDefinedFunctor::AstUserDefinedFunctor () inline
Definition at line 365 of file AstArgument.h.
Referenced by clone().
 {}
souffle::AstUserDefinedFunctor::AstUserDefinedFunctor (const std::string & name) inline
Definition at line 367 of file AstArgument.h.
 : name(name) {}
souffle::AstUserDefinedFunctor::~AstUserDefinedFunctor () override default
Member Function Documentation
void souffle::AstUserDefinedFunctor::add (std::unique_ptr< AstArgument > arg) inline
add argument to argument list
Definition at line 397 of file AstArgument.h.
References args.
{
         args.push_back(std::move(arg));
     }
void souffle::AstUserDefinedFunctor::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 418 of file AstArgument.h.
References args, and map.
{
         for (auto& arg : args) {
             arg = map(std::move(arg));
         }
     }
AstUserDefinedFunctor* souffle::AstUserDefinedFunctor::clone () const inline override virtual
Create clone.
Implements souffle::AstArgument.
Definition at line 407 of file AstArgument.h.
References args, AstUserDefinedFunctor(), getName(), and souffle::AstNode::getSrcLoc().
{
         auto res = new AstUserDefinedFunctor();
         for (auto& cur : args) {
             res->args.push_back(std::unique_ptr<AstArgument>(cur->clone()));
         }
         res->setSrcLoc(getSrcLoc());
         res->setName(getName());
         return res;
     }
bool souffle::AstUserDefinedFunctor::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 435 of file AstArgument.h.
References args, souffle::equal_targets(), and name.
{
         assert(nullptr != dynamic_cast<const AstUserDefinedFunctor*>(&node));
         const auto& other = static_cast<const AstUserDefinedFunctor&>(node);
         return name == other.name && equal_targets(args, other.args);
     }
const AstArgument* souffle::AstUserDefinedFunctor::getArg (size_t idx) const inline
get argument
Definition at line 382 of file AstArgument.h.
References args.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return args[idx].get();
     }
size_t souffle::AstUserDefinedFunctor::getArgCount () const inline
get number of arguments
Definition at line 387 of file AstArgument.h.
References args.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return args.size();
     }
std::vector<AstArgument*> souffle::AstUserDefinedFunctor::getArguments () const inline
get arguments
Definition at line 392 of file AstArgument.h.
References args, and souffle::toPtrVector().
Referenced by souffle::getGroundedTerms(), and souffle::AstTranslator::translateValue().
{
         return toPtrVector(args);
     }
std::vector<const AstNode*> souffle::AstUserDefinedFunctor::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Reimplemented from souffle::AstArgument.
Definition at line 425 of file AstArgument.h.
References args, and souffle::AstArgument::getChildNodes().
{
         auto res = AstArgument::getChildNodes();
         for (auto& cur : args) {
             res.push_back(cur.get());
         }
         return res;
     }
const std::string& souffle::AstUserDefinedFunctor::getName () const inline
get name
Definition at line 372 of file AstArgument.h.
References name.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkProgram(), clone(), and souffle::AstTranslator::translateValue().
{
         return name;
     }
void souffle::AstUserDefinedFunctor::print (std::ostream & os) const inline override virtual
print user-defined functor
Implements souffle::AstNode.
Definition at line 402 of file AstArgument.h.
References args, souffle::join(), and name.
{
         os << '@' << name << "(" << join(args, ",", print_deref<std::unique_ptr<AstArgument>>()) << ")";
     }
void souffle::AstUserDefinedFunctor::setName (const std::string & n) inline
set name
Definition at line 377 of file AstArgument.h.
References n, and name.
{
         name = n;
     }
Field Documentation
std::vector<std::unique_ptr<AstArgument> > souffle::AstUserDefinedFunctor::args protected
arguments of user-defined functor
Definition at line 362 of file AstArgument.h.
Referenced by add(), apply(), clone(), equal(), getArg(), getArgCount(), getArguments(), getChildNodes(), and print().
std::string souffle::AstUserDefinedFunctor::name protected
name of user-defined functor
Definition at line 359 of file AstArgument.h.
Referenced by equal(), getName(), print(), and setName().
The documentation for this class was generated from the following file:
AstArgument.h