souffle: souffle::AstTranslator::ValueIndex Class Reference
souffle::AstTranslator::ValueIndex Class Reference
A class indexing the location of variables and record references within a loop nest resulting from the conversion of a rule.
Public Member Functions
void addVarReference (const AstVariable &var, const Location &l)
void addVarReference (const AstVariable &var, int level, int pos, const std::string &name="")
const Location & getAggregatorLocation (const AstAggregator &agg) const
const Location & getDefinitionPoint (const AstVariable &var) const
const Location & getDefinitionPoint (const AstRecordInit &init) const
int getRecordUnpackLevel (const AstRecordInit &init) const
const variable_reference_map & getVariableReferences () const
bool isDefined (const AstVariable &var) const
bool isSomethingDefinedOn (int level) const
void print (std::ostream &out) const
void setAggregatorLocation (const AstAggregator &agg, const Location &loc)
void setRecordDefinition (const AstRecordInit &init, const Location &l)
void setRecordDefinition (const AstRecordInit &init, int level, int pos, std::string name="")
void setRecordUnpackLevel (const AstRecordInit &init, int level)
Private Types
using aggregator_location_map = std::vector< std::pair< const AstAggregator *, Location >>
A map from AstAggregators to storage locations.
using record_definition_map = std::map< const AstRecordInit *, Location >
The type mapping record init expressions to their definition points, hence the point where they get grounded/bound.
using record_unpack_map = std::map< const AstRecordInit *, int >
The type mapping record init expressions to the loop level where they get unpacked.
using variable_reference_map = std::map< std::string, std::set< Location >>
The type mapping variables (referenced by their names) to the locations where they are used.
Private Attributes
aggregator_location_map aggregator_locations
The level of a nested ram operation that is handling a given aggregator operation.
record_definition_map record_definitions
The index of record definition points.
record_unpack_map record_unpacks
The index of record-unpack levels.
variable_reference_map var_references
The index of variable accesses.
Friends
std::ostream & operator<< (std::ostream &out, const ValueIndex &index) __attribute__((unused))
Detailed Description
A class indexing the location of variables and record references within a loop nest resulting from the conversion of a rule.
Definition at line 93 of file AstTranslator.h.
Member Typedef Documentation
using souffle::AstTranslator::ValueIndex::aggregator_location_map = std::vector<std::pair<const AstAggregator*, Location>> private
A map from AstAggregators to storage locations.
Note, since in this case AstAggregators are indexed by their values (not their address) no standard map can be utilized.
Definition at line 117 of file AstTranslator.h.
using souffle::AstTranslator::ValueIndex::record_definition_map = std::map<const AstRecordInit*, Location> private
The type mapping record init expressions to their definition points, hence the point where they get grounded/bound.
Definition at line 104 of file AstTranslator.h.
using souffle::AstTranslator::ValueIndex::record_unpack_map = std::map<const AstRecordInit*, int> private
The type mapping record init expressions to the loop level where they get unpacked.
Definition at line 110 of file AstTranslator.h.
using souffle::AstTranslator::ValueIndex::variable_reference_map = std::map<std::string, std::set<Location>> private
The type mapping variables (referenced by their names) to the locations where they are used.
Definition at line 98 of file AstTranslator.h.
Member Function Documentation
void souffle::AstTranslator::ValueIndex::addVarReference (const AstVariable & var, const Location & l) inline
Definition at line 134 of file AstTranslator.h.
References souffle::AstVariable::getName(), and var_references.
Referenced by addVarReference().
{
             std::set<Location>& locs = var_references[var.getName()];
             locs.insert(l);
         }
void souffle::AstTranslator::ValueIndex::addVarReference (const AstVariable & var, int level, int pos, const std::string & name = "") inline
Definition at line 139 of file AstTranslator.h.
References addVarReference().
{
             addVarReference(var, Location({level, pos, name}));
         }
const Location& souffle::AstTranslator::ValueIndex::getAggregatorLocation (const AstAggregator & agg) const inline
Definition at line 201 of file AstTranslator.h.
References aggregator_locations.
Referenced by souffle::AstTranslator::translateValue().
{
             // search list
             for (const auto& cur : aggregator_locations) {
                 if (*cur.first == agg) {
                     return cur.second;
                 }
             }
             // fail
             std::cout << "Lookup of " << &agg << " = " << agg << " failed\n";
             assert(false && "Requested aggregation operation is not processed!");
             const static Location fail = Location();
             return fail;
         }
const Location& souffle::AstTranslator::ValueIndex::getDefinitionPoint (const AstVariable & var) const inline
Definition at line 147 of file AstTranslator.h.
References souffle::AstVariable::getName(), and var_references.
Referenced by souffle::AstTranslator::translateValue().
{
             auto pos = var_references.find(var.getName());
             assert(pos != var_references.end() && "Undefined variable referenced!");
             return *pos->second.begin();
         }
const Location& souffle::AstTranslator::ValueIndex::getDefinitionPoint (const AstRecordInit & init) const inline
Definition at line 169 of file AstTranslator.h.
References record_definitions.
{
             auto pos = record_definitions.find(&init);
             if (pos != record_definitions.end()) {
                 return pos->second;
             }
             assert(false && "Requested location for undefined record!");
             static Location fail;
             return fail;
         }
int souffle::AstTranslator::ValueIndex::getRecordUnpackLevel (const AstRecordInit & init) const inline
Definition at line 186 of file AstTranslator.h.
References record_unpacks.
{
             auto pos = record_unpacks.find(&init);
             if (pos != record_unpacks.end()) {
                 return pos->second;
             }
             assert(false && "Requested record is not unpacked properly!");
             return 0;
         }
const variable_reference_map& souffle::AstTranslator::ValueIndex::getVariableReferences () const inline
Definition at line 153 of file AstTranslator.h.
References var_references.
{
             return var_references;
         }
bool souffle::AstTranslator::ValueIndex::isDefined (const AstVariable & var) const inline
Definition at line 143 of file AstTranslator.h.
References souffle::AstVariable::getName(), and var_references.
Referenced by souffle::AstTranslator::translateValue().
{
             return var_references.find(var.getName()) != var_references.end();
         }
bool souffle::AstTranslator::ValueIndex::isSomethingDefinedOn (int level) const inline
Definition at line 219 of file AstTranslator.h.
References record_definitions, and var_references.
{
             // check for variable definitions
             for (const auto& cur : var_references) {
                 if (cur.second.begin()->level == level) {
                     return true;
                 }
             }
             // check for record definitions
             for (const auto& cur : record_definitions) {
                 if (cur.second.level == level) {
                     return true;
                 }
             }
             // nothing defined on this level
             return false;
         }
void souffle::AstTranslator::ValueIndex::print (std::ostream & out) const inline
Definition at line 236 of file AstTranslator.h.
References souffle::join(), and var_references.
{
             out << "Variables:\n\t";
             out << join(var_references, "\n\t");
         }
void souffle::AstTranslator::ValueIndex::setAggregatorLocation (const AstAggregator & agg, const Location & loc) inline
Definition at line 197 of file AstTranslator.h.
References aggregator_locations.
{
             aggregator_locations.push_back(std::make_pair(&agg, loc));
         }
void souffle::AstTranslator::ValueIndex::setRecordDefinition (const AstRecordInit & init, const Location & l) inline
Definition at line 161 of file AstTranslator.h.
References l, and record_definitions.
Referenced by setRecordDefinition().
{
             record_definitions[&init] = l;
         }
void souffle::AstTranslator::ValueIndex::setRecordDefinition (const AstRecordInit & init, int level, int pos, std::string name = "") inline
Definition at line 165 of file AstTranslator.h.
References setRecordDefinition().
{
             setRecordDefinition(init, Location({level, pos, std::move(name)}));
         }
void souffle::AstTranslator::ValueIndex::setRecordUnpackLevel (const AstRecordInit & init, int level) inline
Definition at line 182 of file AstTranslator.h.
References record_unpacks.
{
             record_unpacks[&init] = level;
         }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const ValueIndex & index) friend
Definition at line 241 of file AstTranslator.h.
{
             index.print(out);
             return out;
         }
Field Documentation
aggregator_location_map souffle::AstTranslator::ValueIndex::aggregator_locations private
The level of a nested ram operation that is handling a given aggregator operation.
Definition at line 129 of file AstTranslator.h.
Referenced by getAggregatorLocation(), and setAggregatorLocation().
record_definition_map souffle::AstTranslator::ValueIndex::record_definitions private
The index of record definition points.
Definition at line 123 of file AstTranslator.h.
Referenced by getDefinitionPoint(), isSomethingDefinedOn(), and setRecordDefinition().
record_unpack_map souffle::AstTranslator::ValueIndex::record_unpacks private
The index of record-unpack levels.
Definition at line 126 of file AstTranslator.h.
Referenced by getRecordUnpackLevel(), and setRecordUnpackLevel().
variable_reference_map souffle::AstTranslator::ValueIndex::var_references private
The index of variable accesses.
Definition at line 120 of file AstTranslator.h.
Referenced by addVarReference(), getDefinitionPoint(), getVariableReferences(), isDefined(), isSomethingDefinedOn(), and print().
The documentation for this class was generated from the following file:
AstTranslator.h