souffle: souffle::ReorderLiteralsTransformer Class Reference
souffle::ReorderLiteralsTransformer Class Reference
Transformation pass to reorder body literals.
#include <AstTransforms.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to reorder body literals.
Definition at line 297 of file AstTransforms.h.
Member Function Documentation
std::string souffle::ReorderLiteralsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 302 of file AstTransforms.h.
{
         return "ReorderLiteralsTransformer";
     }
bool souffle::ReorderLiteralsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 1661 of file AstTransforms.cpp.
References souffle::applySIPS(), souffle::Global::config(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstAtom::getName(), souffle::getNextAtomSIPS(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), souffle::getSIPSfunction(), i, souffle::isProposition(), and souffle::numBoundArguments().
{
     bool changed = false;
     AstProgram& program = *translationUnit.getProgram();
     // --- Reordering --- : Prepend Propositions
     auto prependPropositions = [&](AstClause* clause) {
         const std::vector<AstAtom*>& atoms = clause->getAtoms();
         // Calculate the new ordering
         std::vector<unsigned int> nonPropositionIndices;
         std::vector<unsigned int> newOrder;
         bool seenNonProp = false;
         for (unsigned int i = 0; i < atoms.size(); i++) {
             if (isProposition(atoms[i])) {
                 newOrder.push_back(i);
                 if (seenNonProp) {
                     changed = true;
                 }
             } else {
                 nonPropositionIndices.push_back(i);
                 seenNonProp = true;
             }
         }
         for (unsigned int idx : nonPropositionIndices) {
             newOrder.push_back(idx);
         }
         // Reorder the clause accordingly
         clause->reorderAtoms(newOrder);
     };
     // Literal reordering is a rule-local transformation
     for (const AstRelation* rel : program.getRelations()) {
         for (AstClause* clause : rel->getClauses()) {
             // Ignore clauses with fixed execution plans
             if (clause->hasFixedExecutionPlan()) {
                 continue;
             }
             // Prepend propositions
             prependPropositions(clause);
             if (Global::config().has("SIPS")) {
                 // Grab the atoms in the clause
                 std::vector<AstAtom*> atoms = clause->getAtoms();
                 // Decide which SIPS to use
                 std::function<unsigned int(std::vector<AstAtom*>, const std::set<std::string>&)>
                         getNextAtomSIPS = getSIPSfunction(Global::config().get("SIPS"));
                 // Apply the SIPS to get a new ordering
                 std::vector<unsigned int> newOrdering = applySIPS(getNextAtomSIPS, atoms);
                 // Check if we have a change
                 for (unsigned int i = 0; !changed && i < newOrdering.size(); i++) {
                     if (newOrdering[i] != i) {
                         changed = true;
                     }
                 }
                 // Reorder the clause accordingly
                 clause->reorderAtoms(newOrdering);
             }
         }
     }
     // Profile-Guided Reordering
     if (Global::config().has("profile-use")) {
         auto* profileUse = translationUnit.getAnalysis<AstProfileUse>();
         auto profilerSIPS = [&](std::vector<AstAtom*> atoms, const std::set<std::string>& boundVariables) {
             double currOptimalVal = -1;
             unsigned int currOptimalIdx = 0;
             bool set = false;
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 if (atoms[i] == nullptr) {
                     // Already processed, move on
                     continue;
                 }
                 AstAtom* atom = atoms[i];
                 if (isProposition(atom)) {
                     return i;
                 }
                 int numBound = numBoundArguments(atoms[i], boundVariables);
                 int numArgs = atoms[i]->getArity();
                 int numFree = numArgs - numBound;
                 double value = log(profileUse->getRelationSize(atom->getName()));
                 value *= (numFree * 1.0) / numArgs;
                 if (!set || value < currOptimalVal) {
                     set = true;
                     currOptimalVal = value;
                     currOptimalIdx = i;
                 }
             }
             return currOptimalIdx;
         };
         // TODO (azreika): pull out to a function
         for (AstRelation* rel : program.getRelations()) {
             for (AstClause* clause : rel->getClauses()) {
                 if (clause->hasFixedExecutionPlan()) {
                     continue;
                 }
                 std::vector<AstAtom*> atoms = clause->getAtoms();
                 std::vector<unsigned int> newOrdering = applySIPS(profilerSIPS, atoms);
                 // Check if we have a change
                 for (unsigned int i = 0; !changed && i < newOrdering.size(); i++) {
                     if (newOrdering[i] != i) {
                         changed = true;
                     }
                 }
                 // Reorder the clause accordingly
                 clause->reorderAtoms(newOrdering);
             }
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
AstTransforms.h
AstTransforms.cpp