souffle: souffle::RamInsert Class Reference
souffle::RamInsert Class Reference
A relational algebra query TODO (#541): Rename RAM statement: it is used for projection and sub-routines.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamInsert * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamCondition * getCondition () const
Get RAM condition.
const RamOperation & getOperation () const
Get RAM operation.
void print (std::ostream &os, int tabpos) const override
Pretty print.
RamInsert (std::unique_ptr< RamOperation > o, std::unique_ptr< RamCondition > c=nullptr)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM statement.
RamStatement (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamCondition > condition
RAM condition.
std::unique_ptr< RamOperation > operation
RAM operation.
Detailed Description
A relational algebra query TODO (#541): Rename RAM statement: it is used for projection and sub-routines.
Definition at line 413 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamInsert::RamInsert (std::unique_ptr< RamOperation > o, std::unique_ptr< RamCondition > c = nullptr) inline
Definition at line 422 of file RamStatement.h.
Referenced by clone().
             : RamStatement(RN_Insert), operation(std::move(o)), condition(std::move(c)) {}
Member Function Documentation
void souffle::RamInsert::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 466 of file RamStatement.h.
References condition, map, and operation.
{
         operation = map(std::move(operation));
         condition = map(std::move(condition));
     }
RamInsert* souffle::RamInsert::clone () const inline override virtual
Create clone.
Implements souffle::RamStatement.
Definition at line 454 of file RamStatement.h.
References condition, operation, and RamInsert().
{
         RamInsert* res;
         if (condition != nullptr) {
             res = new RamInsert(std::unique_ptr<RamOperation>(operation->clone()));
         } else {
             res = new RamInsert(std::unique_ptr<RamOperation>(operation->clone()),
                     std::unique_ptr<RamCondition>(condition->clone()));
         }
         return res;
     }
bool souffle::RamInsert::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 473 of file RamStatement.h.
References getCondition(), and getOperation().
{
         assert(nullptr != dynamic_cast<const RamInsert*>(&node));
         const auto& other = static_cast<const RamInsert&>(node);
         return getOperation() == other.getOperation() && getCondition() == other.getCondition();
     }
std::vector<const RamNode*> souffle::RamInsert::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 449 of file RamStatement.h.
References condition, and operation.
{
         return std::vector<const RamNode*>({operation.get(), condition.get()});
     }
const RamCondition* souffle::RamInsert::getCondition () const inline
Get RAM condition.
Definition at line 432 of file RamStatement.h.
References condition.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalStmt().
{
         return condition.get();
     }
const RamOperation& souffle::RamInsert::getOperation () const inline
Get RAM operation.
Definition at line 426 of file RamStatement.h.
References operation.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalStmt().
{
         assert(operation);
         return *operation;
     }
void souffle::RamInsert::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print.
Implements souffle::RamStatement.
Definition at line 437 of file RamStatement.h.
References condition, and operation.
{
         os << std::string(tabpos, '\t');
         os << "INSERT ";
         if (condition != nullptr) {
             os << "WHERE ";
             condition->print(os);
         }
         os << "\n";
         operation->print(os, tabpos + 1);
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamInsert::condition protected
RAM condition.
Definition at line 419 of file RamStatement.h.
Referenced by apply(), clone(), getChildNodes(), getCondition(), and print().
std::unique_ptr<RamOperation> souffle::RamInsert::operation protected
RAM operation.
Definition at line 416 of file RamStatement.h.
Referenced by apply(), clone(), getChildNodes(), getOperation(), and print().
The documentation for this class was generated from the following file:
RamStatement.h