souffle: souffle::AstTernaryFunctor Class Reference
souffle::AstTernaryFunctor Class Reference
#include <AstArgument.h>
Public Member Functions
bool acceptsNumbers (int arg) const
Check if the arguments of this functor are number types.
bool acceptsSymbols (int arg) const
Check if the arguments of this functor are symbol types.
void apply (const AstNodeMapper &map) override
Mutates this node.
AstTernaryFunctor (TernaryOp fun, std::unique_ptr< AstArgument > a1, std::unique_ptr< AstArgument > a2, std::unique_ptr< AstArgument > a3)
AstTernaryFunctor * clone () const override
Clone this node.
AstArgument * getArg (int idx) const
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
TernaryOp getFunction () const
bool isNumerical () const
Check if the return value of this functor is a number type.
bool isSymbolic () const
Check if the return value of this functor is a symbol type.
void print (std::ostream &os) const override
Print argument to the given output stream.
Public Member Functions inherited from souffle::AstArgument
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
std::array< std::unique_ptr
< AstArgument >, 3 > arg
TernaryOp fun
Detailed Description
Definition at line 542 of file AstArgument.h.
Constructor & Destructor Documentation
souffle::AstTernaryFunctor::AstTernaryFunctor (TernaryOp fun, std::unique_ptr< AstArgument > a1, std::unique_ptr< AstArgument > a2, std::unique_ptr< AstArgument > a3) inline
Definition at line 548 of file AstArgument.h.
Referenced by clone().
             : fun(fun), arg({{std::move(a1), std::move(a2), std::move(a3)}}) {}
Member Function Documentation
bool souffle::AstTernaryFunctor::acceptsNumbers (int arg) const inline
Check if the arguments of this functor are number types.
Definition at line 574 of file AstArgument.h.
References fun, and souffle::ternaryOpAcceptsNumbers().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return ternaryOpAcceptsNumbers(arg, fun);
     }
bool souffle::AstTernaryFunctor::acceptsSymbols (int arg) const inline
Check if the arguments of this functor are symbol types.
Definition at line 579 of file AstArgument.h.
References fun, and souffle::ternaryOpAcceptsSymbols().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return ternaryOpAcceptsSymbols(arg, fun);
     }
void souffle::AstTernaryFunctor::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 604 of file AstArgument.h.
References arg, and map.
{
         arg[0] = map(std::move(arg[0]));
         arg[1] = map(std::move(arg[1]));
         arg[2] = map(std::move(arg[2]));
     }
AstTernaryFunctor* souffle::AstTernaryFunctor::clone () const inline override virtual
Clone this node.
Implements souffle::AstArgument.
Definition at line 596 of file AstArgument.h.
References arg, AstTernaryFunctor(), fun, and souffle::AstNode::getSrcLoc().
{
         auto res = new AstTernaryFunctor(fun, std::unique_ptr<AstArgument>(arg[0]->clone()),
                 std::unique_ptr<AstArgument>(arg[1]->clone()), std::unique_ptr<AstArgument>(arg[2]->clone()));
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstTernaryFunctor::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 621 of file AstArgument.h.
References arg, and fun.
{
         assert(nullptr != dynamic_cast<const AstTernaryFunctor*>(&node));
         const auto& other = static_cast<const AstTernaryFunctor&>(node);
         return fun == other.fun && *arg[0] == *other.arg[0] && *arg[1] == *other.arg[1] &&
                *arg[2] == *other.arg[2];
     }
AstArgument* souffle::AstTernaryFunctor::getArg (int idx) const inline
Definition at line 554 of file AstArgument.h.
References arg.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkProgram(), souffle::getGroundedTerms(), and souffle::AstTranslator::translateValue().
{
         assert(idx >= 0 && idx < 3 && "wrong argument");
         return arg[idx].get();
     }
std::vector<const AstNode*> souffle::AstTernaryFunctor::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Reimplemented from souffle::AstArgument.
Definition at line 611 of file AstArgument.h.
References arg, and souffle::AstArgument::getChildNodes().
{
         auto res = AstArgument::getChildNodes();
         res.push_back(arg[0].get());
         res.push_back(arg[1].get());
         res.push_back(arg[2].get());
         return res;
     }
TernaryOp souffle::AstTernaryFunctor::getFunction () const inline
Definition at line 559 of file AstArgument.h.
References fun.
Referenced by souffle::AstTranslator::translateValue().
{
         return fun;
     }
bool souffle::AstTernaryFunctor::isNumerical () const inline
Check if the return value of this functor is a number type.
Definition at line 564 of file AstArgument.h.
References fun, and souffle::isNumericTernaryOp().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return isNumericTernaryOp(fun);
     }
bool souffle::AstTernaryFunctor::isSymbolic () const inline
Check if the return value of this functor is a symbol type.
Definition at line 569 of file AstArgument.h.
References fun, and souffle::isSymbolicTernaryOp().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return isSymbolicTernaryOp(fun);
     }
void souffle::AstTernaryFunctor::print (std::ostream & os) const inline override virtual
Print argument to the given output stream.
Implements souffle::AstNode.
Definition at line 584 of file AstArgument.h.
References arg, fun, and souffle::getSymbolForTernaryOp().
{
         os << getSymbolForTernaryOp(fun);
         os << "(";
         arg[0]->print(os);
         os << ",";
         arg[1]->print(os);
         os << ",";
         arg[2]->print(os);
         os << ")";
     }
Field Documentation
std::array<std::unique_ptr<AstArgument>, 3> souffle::AstTernaryFunctor::arg protected
Definition at line 545 of file AstArgument.h.
Referenced by apply(), clone(), equal(), getArg(), getChildNodes(), and print().
TernaryOp souffle::AstTernaryFunctor::fun protected
Definition at line 544 of file AstArgument.h.
Referenced by acceptsNumbers(), acceptsSymbols(), clone(), equal(), getFunction(), isNumerical(), isSymbolic(), and print().
The documentation for this class was generated from the following file:
AstArgument.h