souffle: souffle::AstBinaryFunctor Class Reference
souffle::AstBinaryFunctor Class Reference
Subclass of Argument that represents a binary function.
#include <AstArgument.h>
Public Member Functions
bool acceptsNumbers (int arg) const
Check if the arguments of this functor are number types.
bool acceptsSymbols (int arg) const
Check if the arguments of this functor are symbol types.
void apply (const AstNodeMapper &map) override
Mutates this node.
AstBinaryFunctor (BinaryOp fun, std::unique_ptr< AstArgument > l, std::unique_ptr< AstArgument > r)
AstBinaryFunctor * clone () const override
Creates a clone.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
BinaryOp getFunction () const
AstArgument * getLHS () const
AstArgument * getRHS () const
bool isNumerical () const
Check if the return value of this functor is a number type.
bool isSymbolic () const
Check if the return value of this functor is a symbol type.
void print (std::ostream &os) const override
Print argument to the given output stream.
~AstBinaryFunctor () override=default
Public Member Functions inherited from souffle::AstArgument
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
BinaryOp fun
std::unique_ptr< AstArgument > lhs
std::unique_ptr< AstArgument > rhs
Detailed Description
Subclass of Argument that represents a binary function.
Definition at line 445 of file AstArgument.h.
Constructor & Destructor Documentation
souffle::AstBinaryFunctor::AstBinaryFunctor (BinaryOp fun, std::unique_ptr< AstArgument > l, std::unique_ptr< AstArgument > r) inline
Definition at line 452 of file AstArgument.h.
Referenced by clone().
             : fun(fun), lhs(std::move(l)), rhs(std::move(r)) {}
souffle::AstBinaryFunctor::~AstBinaryFunctor () override default
Member Function Documentation
bool souffle::AstBinaryFunctor::acceptsNumbers (int arg) const inline
Check if the arguments of this functor are number types.
Definition at line 480 of file AstArgument.h.
References souffle::binaryOpAcceptsNumbers(), and fun.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return binaryOpAcceptsNumbers(arg, fun);
     }
bool souffle::AstBinaryFunctor::acceptsSymbols (int arg) const inline
Check if the arguments of this functor are symbol types.
Definition at line 485 of file AstArgument.h.
References souffle::binaryOpAcceptsSymbols(), and fun.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return binaryOpAcceptsSymbols(arg, fun);
     }
void souffle::AstBinaryFunctor::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 516 of file AstArgument.h.
References lhs, map, and rhs.
{
         lhs = map(std::move(lhs));
         rhs = map(std::move(rhs));
     }
AstBinaryFunctor* souffle::AstBinaryFunctor::clone () const inline override virtual
Creates a clone.
Implements souffle::AstArgument.
Definition at line 508 of file AstArgument.h.
References AstBinaryFunctor(), fun, souffle::AstNode::getSrcLoc(), lhs, and rhs.
{
         auto res = new AstBinaryFunctor(
                 fun, std::unique_ptr<AstArgument>(lhs->clone()), std::unique_ptr<AstArgument>(rhs->clone()));
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstBinaryFunctor::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 531 of file AstArgument.h.
References fun, lhs, and rhs.
{
         assert(nullptr != dynamic_cast<const AstBinaryFunctor*>(&node));
         const auto& other = static_cast<const AstBinaryFunctor&>(node);
         return fun == other.fun && *lhs == *other.lhs && *rhs == *other.rhs;
     }
std::vector<const AstNode*> souffle::AstBinaryFunctor::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Reimplemented from souffle::AstArgument.
Definition at line 522 of file AstArgument.h.
References souffle::AstArgument::getChildNodes(), lhs, and rhs.
{
         auto res = AstArgument::getChildNodes();
         res.push_back(lhs.get());
         res.push_back(rhs.get());
         return res;
     }
BinaryOp souffle::AstBinaryFunctor::getFunction () const inline
Definition at line 465 of file AstArgument.h.
References fun.
Referenced by souffle::AstTranslator::translateValue().
{
         return fun;
     }
AstArgument* souffle::AstBinaryFunctor::getLHS () const inline
Definition at line 457 of file AstArgument.h.
References lhs.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkProgram(), souffle::getGroundedTerms(), and souffle::AstTranslator::translateValue().
{
         return lhs.get();
     }
AstArgument* souffle::AstBinaryFunctor::getRHS () const inline
Definition at line 461 of file AstArgument.h.
References rhs.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkProgram(), souffle::getGroundedTerms(), and souffle::AstTranslator::translateValue().
{
         return rhs.get();
     }
bool souffle::AstBinaryFunctor::isNumerical () const inline
Check if the return value of this functor is a number type.
Definition at line 470 of file AstArgument.h.
References fun, and souffle::isNumericBinaryOp().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return isNumericBinaryOp(fun);
     }
bool souffle::AstBinaryFunctor::isSymbolic () const inline
Check if the return value of this functor is a symbol type.
Definition at line 475 of file AstArgument.h.
References fun, and souffle::isSymbolicBinaryOp().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return isSymbolicBinaryOp(fun);
     }
void souffle::AstBinaryFunctor::print (std::ostream & os) const inline override virtual
Print argument to the given output stream.
Implements souffle::AstNode.
Definition at line 490 of file AstArgument.h.
References fun, souffle::getSymbolForBinaryOp(), lhs, souffle::MAX, and rhs.
{
         if (fun < BinaryOp::MAX) {
             os << "(";
             lhs->print(os);
             os << getSymbolForBinaryOp(fun);
             rhs->print(os);
             os << ")";
         } else {
             os << getSymbolForBinaryOp(fun);
             os << "(";
             lhs->print(os);
             os << ",";
             rhs->print(os);
             os << ")";
         }
     }
Field Documentation
BinaryOp souffle::AstBinaryFunctor::fun protected
Definition at line 447 of file AstArgument.h.
Referenced by acceptsNumbers(), acceptsSymbols(), clone(), equal(), getFunction(), isNumerical(), isSymbolic(), and print().
std::unique_ptr<AstArgument> souffle::AstBinaryFunctor::lhs protected
Definition at line 448 of file AstArgument.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getLHS(), and print().
std::unique_ptr<AstArgument> souffle::AstBinaryFunctor::rhs protected
Definition at line 449 of file AstArgument.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getRHS(), and print().
The documentation for this class was generated from the following file:
AstArgument.h