souffle: souffle::RamDebugInfo Class Reference
souffle::RamDebugInfo Class Reference
Debug statement.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamDebugInfo * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const std::string & getMessage () const
Get debugging message.
const RamStatement & getStatement () const
Get debugging statement.
void print (std::ostream &os, int tabpos) const override
Pretty print.
RamDebugInfo (std::unique_ptr< RamStatement > stmt, std::string msg)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM statement.
RamStatement (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::string message
debugging message
std::unique_ptr< RamStatement > statement
debugging statement
Detailed Description
Debug statement.
Definition at line 829 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamDebugInfo::RamDebugInfo (std::unique_ptr< RamStatement > stmt, std::string msg) inline
Definition at line 838 of file RamStatement.h.
References statement.
Referenced by clone().
             : RamStatement(RN_DebugInfo), statement(std::move(stmt)), message(std::move(msg)) {
         assert(statement);
     }
Member Function Documentation
void souffle::RamDebugInfo::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 876 of file RamStatement.h.
References map, and statement.
{
         statement = map(std::move(statement));
     }
RamDebugInfo* souffle::RamDebugInfo::clone () const inline override virtual
Create clone.
Implements souffle::RamStatement.
Definition at line 870 of file RamStatement.h.
References message, RamDebugInfo(), and statement.
{
         RamDebugInfo* res = new RamDebugInfo(std::unique_ptr<RamStatement>(statement->clone()), message);
         return res;
     }
bool souffle::RamDebugInfo::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 882 of file RamStatement.h.
References getMessage(), and getStatement().
{
         assert(nullptr != dynamic_cast<const RamLogTimer*>(&node));
         const auto& other = static_cast<const RamLogTimer&>(node);
         return getStatement() == other.getStatement() && getMessage() == other.getMessage();
     }
std::vector<const RamNode*> souffle::RamDebugInfo::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 865 of file RamStatement.h.
References statement.
{
         return toVector<const RamNode*>(statement.get());
     }
const std::string& souffle::RamDebugInfo::getMessage () const inline
Get debugging message.
Definition at line 844 of file RamStatement.h.
References message.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalStmt().
{
         return message;
     }
const RamStatement& souffle::RamDebugInfo::getStatement () const inline
Get debugging statement.
Definition at line 849 of file RamStatement.h.
References statement.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalStmt().
{
         assert(statement);
         return *statement;
     }
void souffle::RamDebugInfo::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print.
Implements souffle::RamStatement.
Definition at line 855 of file RamStatement.h.
References message, statement, and souffle::stringify().
{
         os << std::string(tabpos, '\t');
         os << "BEGIN_DEBUG \"" << stringify(message) << "\"\n";
         statement->print(os, tabpos + 1);
         os << "\n";
         os << std::string(tabpos, '\t');
         os << "END_DEBUG";
     }
Field Documentation
std::string souffle::RamDebugInfo::message protected
debugging message
Definition at line 835 of file RamStatement.h.
Referenced by clone(), getMessage(), and print().
std::unique_ptr<RamStatement> souffle::RamDebugInfo::statement protected
debugging statement
Definition at line 832 of file RamStatement.h.
Referenced by apply(), clone(), getChildNodes(), getStatement(), print(), and RamDebugInfo().
The documentation for this class was generated from the following file:
RamStatement.h